using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using COLID.Graph.TripleStore.DataModels.Base;
using COLID.RegistrationService.Common.DataModel.Validation;
using COLID.RegistrationService.Common.DataModel.Identifier;
using COLID.Graph.Metadata.DataModels.Resources;
using COLID.RegistrationService.Common.DataModels.Search;
using COLID.RegistrationService.Common.DataModels.RelationshipManager;

namespace COLID.RegistrationService.Services.Interface
{
    /// <summary>
    /// Service to handle all identifier related operations.
    /// </summary>
    public interface IIdentifierService
    {
        /// <summary>
        /// Gets a list of all identifier occurences.
        /// </summary>
        /// <param name="pidUri">identifier to search for</param>
        /// <returns>List of <see cref="DuplicateResult"/>, empty list if no occurence</returns>
        IList<DuplicateResult> GetPidUriIdentifierOccurrences(string pidUri);

        /// <summary>
        /// Deletes all identifiers to a given resource entity.
        /// </summary>
        /// <param name="resource">the resource to delete identifiers from</param>
        /// <param name="versions">all available versions of the resource</param>
        void DeleteAllUnpublishedIdentifiers(Entity resource, IList<VersionOverviewCTO> versions);

        /// <summary>
        /// Determine all oprhaned identifiers and returns them in a list. An Identifier is an orphaned one,
        /// if it doesn't have any relation to a pid-uri or base-uri.
        /// </summary>
        /// <returns>A list of orphaned identifiers</returns>
        IList<string> GetOrphanedIdentifiersList();

        /// <summary>
        /// Delete an orphaned identifier which matches the given uri. The <paramref name="identifierUri"/>
        /// will be checken, if it really has no relation, before the identifier will be deleted.
        /// </summary>
        ///
        /// <param name="identifierUri">the uri to check and delete</param>
        ///
        /// <exception cref="ArgumentNullException">if the param is null</exception>
        /// <exception cref="UriFormatException">if the param is not an uri</exception>
        void DeleteOrphanedIdentifier(string identifierUri, bool checkInOrphanedList = true);

        /// <summary>
        /// Delete an multiple orphaned identifier which matches the given uri. The <paramref name="identifierUris"/>
        /// will be checken, if it really has no relation, before the identifier will be deleted.
        /// </summary>
        ///
        /// <param name="identifierUris">the uri to check and delete</param>
        ///
        /// <exception cref="ArgumentNullException">if the param is null</exception>
        /// <exception cref="UriFormatException">if the param is not an uri</exception>
        Task<List<OrphanResultDto>> DeleteOrphanedIdentifierList(IList<string> identifierUris);

        /// <summary>
        /// Register the Saved Search as a PID URI
        /// </summary>
        /// <param name="searchFilterProxyDTORequest">The request from MarketPlace UI with user saved search</param>
        /// <returns>Returns the DTO back with the filled PIDURI generated by this endpoint</returns>
        /// <response code="200">Returns the DTO with newly generated PIDURI</response>
        /// <response code="400">If the given request is invalid</response>
        /// <response code="500">If an unexpected error occurs</response>
        Task<SearchFilterProxyDTO> RegisterSavedSearchAsIdentifier(SearchFilterProxyDTO searchFilterProxyDTORequest);

        /// <summary>
        /// Register the RRM Map as a PID URI
        /// </summary>
        /// <param name="mapProxyDTO">The mapProxyDTO which has mapID from RRM</param>
        /// <returns>Returns the created and registered URI in the DTO</returns>
        /// <response code="200">Returns newly generated PIDURI</response>
        /// <response code="400">If the given request is invalid</response>
        /// <response code="500">If an unexpected error occurs</response>
        Task<MapProxyDTO> RegisterRRMMapAsIdentifier(MapProxyDTO mapProxyDTO);

    }
}
