using System.Collections.Generic;
using COLID.RegistrationService.Common.DataModel.PidUriTemplates;
using COLID.Graph.TripleStore.DataModels.Base;

namespace COLID.RegistrationService.Services.Interface
{
    /// <summary>
    /// Service to handle all pid uri generation related operations.
    /// </summary>
    public interface IPidUriGenerationService
    {
        /// <summary>
        /// Contains all identifiers generated by the instance of the service.
        /// </summary>
        IList<string> GeneratedIdentifier { get; }

        /// <summary>
        /// Method to generate a PID Idenfifier from a specific template.
        /// </summary>
        /// <param name="pidUriTemplateFlat">the flat pid uri template</param>
        /// <param name="resource">the resource entity</param>
        /// <returns></returns>
        string GenerateIdentifierFromTemplate(PidUriTemplateFlattened pidUriTemplateFlat, Entity resource);
    }
}
